-- TEST -21. '인문사회' 계열 과목 교수 이름 출력
SELECT TC.CLASS_NAME, TP.PROFESSOR_NAME
FROM TB_CLASS TC
JOIN TB_CLASS_PROFESSOR TCP ON TC.CLASS_NO = TCP.CLASS_NO
JOIN TB_PROFESSOR TP ON TP.PROFESSOR_NO = TCP.PROFESSOR_NO
WHERE TC.DEPARTMENT_NO IN (SELECT DEPARTMENT_NO
												FROM TB_DEPARTMENT
												WHERE CATEGORY = '인문사회');


-- TEST - 22. 음악학과 학생 평점 조회 (학번, 학생 이름, 전체 평점 출력)
SELECT STUDENT_NO AS "학번", TS.STUDENT_NAME AS "학생 이름", AVG(TG.POINT) AS "전체 평점"
FROM TB_DEPARTMENT TD
JOIN TB_STUDENT TS USING(DEPARTMENT_NO) 
JOIN TB_GRADE TG USING(STUDENT_NO)
WHERE TD.DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, TS.STUDENT_NAME
ORDER BY STUDENT_NO ASC;

-- OR
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생 이름", AVG(POINT) AS "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '음악학과')
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY STUDENT_NO ASC;


-- TEST - 23. 학번 A313047 학생의 학과 이름, 학생 이름, 지도교수 이름 출력
-- (HEADER : '학과이름', '학생이름', '지도교수이름')
SELECT TD.DEPARTMENT_NAME AS "학과이름", TS.STUDENT_NAME AS "학생이름",
TP.PROFESSOR_NAME AS "지도교수이름"
FROM TB_STUDENT TS
JOIN TB_DEPARTMENT TD USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR TP ON TS.COACH_PROFESSOR_NO = TP.PROFESSOR_NO
WHERE TS.STUDENT_NO = 'A313047';


-- TEST - 24. 2007년도 '인간관계론' 수강생의 학생이름 및 수강학기 조회
SELECT TS.STUDENT_NAME, TG.TERM_NO 
FROM TB_STUDENT TS
JOIN TB_GRADE TG USING(STUDENT_NO)
JOIN TB_CLASS TC USING(CLASS_NO)
WHERE TG.TERM_NO LIKE '2007%'
AND TC.CLASS_NAME = '인간관계론';

-- OR
SELECT TS.STUDENT_NAME, TG.TERM_NO 
FROM TB_STUDENT TS
JOIN TB_GRADE TG ON TS.STUDENT_NO = TG.STUDENT_NO
JOIN TB_CLASS TC ON TG.CLASS_NO = TC.CLASS_NO
WHERE TG.TERM_NO LIKE '2007%' AND TC.CLASS_NAME = '인간관계론';


-- TEST - 25. 예체능 계열 과목 중 담당 교수가 배정되지 않은 과목의 이름과 학과 조회
SELECT TC.CLASS_NAME, TD.DEPARTMENT_NAME
FROM TB_DEPARTMENT TD
JOIN TB_CLASS TC USING(DEPARTMENT_NO)
LEFT OUTER JOIN TB_CLASS_PROFESSOR TCP USING(CLASS_NO)
WHERE TD.CATEGORY = '예체능'
AND TCP.PROFESSOR_NO IS NULL;


-- TEST - 26. 서반아어학과 학생 지도교수 조회
-- HEADER : '학생이름', '지도교수'
-- ORDER BY 학번 DESC 
-- 지도교수가 없는 학생일 경우 '지도교수 미지정'으로 표시
SELECT TS.STUDENT_NAME, 
			CASE WHEN TP.PROFESSOR_NAME IS NULL THEN  '지도교수 미지정'
			ELSE TP.PROFESSOR_NAME
			END AS "지도교수"
FROM TB_STUDENT TS
JOIN TB_DEPARTMENT TD USING(DEPARTMENT_NO) 
LEFT JOIN TB_PROFESSOR TP ON TS.COACH_PROFESSOR_NO = PROFESSOR_NO 
WHERE TD.DEPARTMENT_NAME = '서반아어학과'
ORDER BY TS.STUDENT_NO;

-- OR
SELECT TS.STUDENT_NAME,
       COALESCE(TP.PROFESSOR_NAME, '지도교수 미지정') AS "지도교수"
FROM TB_STUDENT TS
JOIN TB_DEPARTMENT TD ON TS.DEPARTMENT_NO = TD.DEPARTMENT_NO
LEFT JOIN TB_PROFESSOR TP ON TS.COACH_PROFESSOR_NO = TP.PROFESSOR_NO
WHERE TD.DEPARTMENT_NAME = '서반아어학과'
ORDER BY TS.STUDENT_NO DESC;



-- TEST- 27. 환경조경학과 전공과목별 평점
SELECT TC.CLASS_NO, TC.CLASS_NAME, AVG(TG.POINT) AS "전체 평점"
FROM TB_CLASS TC
JOIN TB_GRADE TG ON TC.CLASS_NO = TG.CLASS_NO
WHERE TC.DEPARTMENT_NO = (SELECT DEPARTMENT_NO
												FROM TB_DEPARTMENT
												WHERE DEPARTMENT_NAME = '환경조경학과')
AND TC.CLASS_TYPE LIKE '전공%'
GROUP BY TC.CLASS_NO, TC.CLASS_NAME;



--TEST - 28. 환경조경학과 소속 계열 학과들의 학과별 전공과목 평점
-- HEADER : '계열학과명', '전공평점'
-- ROUND(AVG(평점), 1)
SELECT TD.DEPARTMENT_NAME AS "계열 학과명",
			ROUND(AVG(TG.POINT), 1) AS "전공평점"
FROM TB_DEPARTMENT TD
JOIN TB_CLASS TC USING(DEPARTMENT_NO)
JOIN TB_GRADE TG USING(CLASS_NO)
WHERE TD.CATEGORY = (SELECT CATEGORY
								FROM TB_DEPARTMENT 
								WHERE DEPARTMENT_NAME = '환경조경학과')
AND TC.CLASS_TYPE LIKE '전공%'
GROUP BY TD.DEPARTMENT_NAME
ORDER BY 1, 2;