-- TEST  - 1. SUBJECT TABLE 생성
SELECT *
FROM NLS_DATABASE_PARAMETERS
WHERE PARAMETER = 'NLS_CHARACTERSET' OR PARAMETER = 'NLS NCHAR CHARACTERSET';
-- AL32UTF8은 한글을 3 byte로 처리

CREATE TABLE SUBJECT
(SUBNO NUMBER(5) CONSTRAINT SUBJECT_SUBNO_PK PRIMARY KEY,
SUBNAME VARCHAR2(20) CONSTRAINT SUBJECT_SUBNAME_NN NOT NULL,
TERM VARCHAR2(1) CONSTRAINT SUBJECT_TERM_CK CHECK(TERM IN (1, 2)),
TYPE VARCHAR2(6) CONSTRAINT SUBJECT_TYPE_CK CHECK(TYPE IN ('필수', '선택')));

INSERT INTO SUBJECT (SUBNO, SUBNAME, TERM, TYPE)
VALUES(1, 'AA', 1, '필수');


-- TEST - 2. SUGANG TABLE 생성 (STUDENT TABLE 인스턴스 참조)
CREATE TABLE STUDENT
(STUDNO NUMBER(5) CONSTRAINT STUDENT_STUDNO_PK PRIMARY KEY,
STUDAME VARCHAR2(10));

CREATE TABLE SUGANG
(STUDNO NUMBER(5), 
SUBNO NUMBER(5),
REGDATE DATE,
RESUT NUMBER(3),
CONSTRAINT SUGANG_STUDNO_PK PRIMARY KEY(STUDNO, SUBNO),
CONSTRAINT SUGANG_STUDNO_FK FOREIGN KEY(STUDNO) REFERENCES STUDENT(STUDNO), 
CONSTRAINT SUGANG_SUBNO_FK FOREIGN KEY(SUBNO) REFERENCES SUBJECT(SUBNO));
